CURRENT_DIR := canonicalize(justfile_directory())

default:
    just --list

build-client:
    cd client && just build

build-client-release:
    cd client && just build-release

serve:
    concurrently --kill-others \
      "cd ../.. && fd -e rs -e toml | entr -r sh -c 'cd {{ CURRENT_DIR }}/server && cargo run -- {{ CURRENT_DIR }}'" \
      "cd ../.. && fd -e rs -e toml | entr -r sh -c 'cd {{ CURRENT_DIR }} && just build-client'"
