CURRENT_DIR := canonicalize(justfile_directory())

default:
    just --list

build-client:
    cd client && just build

build-client-release:
    cd client && just build-release

serve *args="":
    concurrently --kill-others \
      "cd ../.. && fd -e rs -e toml | entr -r sh -c 'cd {{ CURRENT_DIR }} && cargo run -p server -- {{ args }}'" \
      "cd ../.. && fd -e rs -e toml | entr -r sh -c 'cd {{ CURRENT_DIR }} && just build-client'"
