[workspace]
resolver = "2"
members = [
  "examples/server-and-client/client",
  "examples/server-and-client/server",
  "examples/standalone-client",
]
exclude = []

[workspace.package]
version = "0.1.0"
authors = ["Robert Krahn <robert@hyper.video>"]
edition = "2021"
repository = "https://github.com/hypervideo/metrics-exporter-wasm"

[workspace.dependencies]
axum = "0.8.1"
axum-prometheus = "0.8.0"
color-eyre = "0.6.3"
console_error_panic_hook = "0.1.7"
eyre = "0.6.12"
futures = "0.3.31"
hyper = "1.6.0"
metrics = { version = "0.24.1" }
metrics-exporter-wasm.path = "."
metrics-util = "0.19.0"
portable-atomic = { version = "1.7.0", default-features = false, features = ["fallback"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.138"
tokio = "1.43.0"
tower = "0.5.2"
tower-http = "0.6.2"
tracing = { version = "0.1.0", default-features = false, features = ["attributes"] }
tracing-subscriber = "0.3.18"
wasm-bindgen = { version = "0.2.100", default-features = false }
wasm-bindgen-futures = "0.4.49"
wasm-tracing = { git = "https://github.com/hypervideo/wasm-tracing", rev = "351a117449b51cdbf2b7c51386fe999a37a7efe7" }
web-sys = "0.3.76"

[workspace.dependencies.asn1rs]
git = "https://github.com/hypervideo/asn1rs"
rev = "f101f1315ad80dd60d9d4aabfaf9e567467a2cac"
default-features = false
features = ["macros", "model"]

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# root

[package]
name = "metrics-exporter-wasm"
version.workspace = true
authors.workspace = true
categories = ["development-tools::debugging"]
edition.workspace = true
keywords = ["metrics", "telemetry", "wasm"]
description = "A metrics-compatible exporter meant for browser WASM applications that outputs metrics over HTTP."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
asn1rs.workspace = true
brotli = "7.0.0"
futures.workspace = true
gloo = { version = "0.11.0", default-features = false, features = ["net", "timers", "futures"] }
metrics.workspace = true
portable-atomic.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true
wasm-bindgen-futures.workspace = true
wasmtimer = "0.4.1"
web-sys = { workspace = true, features = ["AbortController"] }

[target.'cfg(target_pointer_width = "32")'.dependencies]
portable-atomic.workspace = true

[build-dependencies]
asn1rs.workspace = true

[features]
default = []
asn-debug = ["asn1rs/descriptive-deserialize-errors", "asn1rs/debug-proc-macro"]

[profile.release-with-debug]
inherits = "release"
debug = true
