[workspace]
resolver = "2"
members = ["examples/metrics-exporter-wasm-example"]
exclude = []

[workspace.package]
version = "0.1.0"
authors = ["Robert Krahn <robert@hyper.video>"]
edition = "2021"
repository = "https://github.com/hypervideo/metrics-exporter-wasm"

[workspace.dependencies]
crossbeam-channel = { version = "0.5.14", features = ["std"] }
metrics = { version = "0.23.0" }
portable-atomic = { version = "1.7.0", default-features = false, features = ["fallback"] }
serde = { version = "1.0.209", features = ["derive"] }

[workspace.dependencies.asn1rs]
git = "https://github.com/hypervideo/asn1rs"
rev = "f101f1315ad80dd60d9d4aabfaf9e567467a2cac"
default-features = false
features = ["macros", "model"]

[workspace.dependencies.web-sys]
version = "0.3.76"
features = ["Performance", "PerformanceEntry", "PerformanceMark", "PerformanceMeasure", "Document", "Window"]

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

[package]
name = "metrics-exporter-wasm"
version.workspace = true
authors.workspace = true
categories = ["development-tools::debugging"]
edition.workspace = true
keywords = ["metrics", "telemetry", "wasm"]
description = "A metrics-compatible exporter meant for browser WASM applications that outputs metrics over HTTP."

[dependencies]
asn1rs.workspace = true
crossbeam-channel.workspace = true
metrics.workspace = true
portable-atomic.workspace = true
serde.workspace = true

[target.'cfg(target_pointer_width = "32")'.dependencies]
portable-atomic.workspace = true

[build-dependencies]
asn1rs.workspace = true

[features]
default = []
asn-debug = ["asn1rs/descriptive-deserialize-errors", "asn1rs/debug-proc-macro"]
