default:
    just --list

build:
    cargo build -p metrics-exporter-wasm-example --target wasm32-unknown-unknown
    rm -rf ./dist
    wasm-bindgen --target web --out-dir dist ../../target/wasm32-unknown-unknown/debug/metrics_exporter_wasm_example.wasm

build-release:
    cargo build -p metrics-exporter-wasm-example --target wasm32-unknown-unknown --release
    rm -rf ./dist
    wasm-bindgen --target web --out-dir dist ../../target/wasm32-unknown-unknown/release/metrics_exporter_wasm_example.wasm
    wasm-opt -O4 ./dist/metrics_exporter_wasm_example_bg.wasm -o ./dist/metrics_exporter_wasm_example_bg.wasm

dev: build
    concurrently --kill-others \
      "fd -e rs | entr just example-build" \
      "live-server --no-browser"

serve: build-release
    http-server
