[package]
name = "server"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish = false
repository.workspace = true

[dependencies]
axum.workspace = true
axum-prometheus.workspace = true
color-eyre.workspace = true
eyre.workspace = true
futures.workspace = true
hyper.workspace = true
metrics-prometheus = "0.9.0"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.features = ["fs"]
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.features = ["env-filter"]
tracing-subscriber.workspace = true
