name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']
defaults:
  run:
    shell: bash
env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install cargo-hack
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-hack
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Run tests
      run: |
        cargo hack test --feature-powerset
